In [1]:
%pip install seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: seaborn in /Users/sufian/Library/Python/3.9/lib/python/site-packages (0.13.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /Users/sufian/Library/Python/3.9/lib/python/site-packages (from seaborn) (3.9.4)
Requirement already satisfied: pandas>=1.2 in /Users/sufian/Library/Python/3.9/lib/python/site-packages (from seaborn) (2.3.3)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /Users/sufian/Library/Python/3.9/lib/python/site-packages (from seaborn) (2.0.2)
Requirement already satisfied: fonttools>=4.22.0 in /Users/sufian/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.60.2)
Requirement already satisfied: python-dateutil>=2.7 in /Users/sufian/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: importlib-resources>=3.2.0 in /Users/sufian/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (6.5.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/sufian/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /Users/sufian/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/sufian/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: pillow>=8 in /Users/sufian/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/sufian/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /Users/sufian/Library/Python/3.9/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: zipp>=3.1.0 in /Users/sufian/Library/Python/3.9/lib/python/site-packages (from importlib-resources>=3.2.0->matplotlib!=3.6.1,>=3.4->seaborn) (3.23.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/sufian/Library/Python/3.9/lib/python/site-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: pytz>=2020.1 in /Users/sufian/Library/Python/3.9/lib/python/site-packages (from pandas>=1.2->seaborn) (2026.3.post1)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.15.0)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [2]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#to display all coulmns, so nothing gets hidden
pd.set_option('display.max_columns', None)

In [3]:
#loading the dataset
df = pd.read_csv('../data/raw/MARVEL vs. DC - IMDB & ROTTEN TOMATOES.csv', encoding='latin1')

#to check the size of the dataset
print(f"Dataset Shape: {df.shape}")

#taking a look at the first 5 rows
df.head()

Dataset Shape: (90, 19)

,Unnamed: 0,title,year,genre,runtime,mpa_rating,imdb_rating,imdb_votes,imdb_gross,director,stars,description,crit_consensus,tomato_meter,tomato_review,tom_aud_score,tom_ratings,entity,id
0,1,Captain America,1944,"Action, Adventure, Sci-Fi",244,Approved,5.5,844,0,Elmer Clifton,"Elmer Clifton,Dick Purcell,Lorna Gray,Lionel A...",Superhero Captain America battles the evil for...,"Find one of these old serials, friend. They're...",0,1,82,250,MARVEL,1
1,2,Howard the Duck,1986,"Action, Adventure, Comedy",110,PG,4.7,44073,16300000,Willard Huyck,"Willard Huyck,Lea Thompson,Jeffrey Jones,Tim R...",A sarcastic humanoid duck is pulled from his h...,"While it has its moments, Howard the Duck suff...",13,78,38,50000,MARVEL,2
2,3,Blade,1998,"Action, Horror, Sci-Fi",120,R,7.1,251243,70090000,Stephen Norrington,"Stephen Norrington,Wesley Snipes,Stephen Dorff...","A half-vampire, half-mortal man becomes a prot...","Though some may find the plot a bit lacking, B...",55,103,78,250000,MARVEL,3
3,4,X-Men,2000,"Action, Adventure, Sci-Fi",104,PG-13,7.4,580354,157300000,Bryan Singer,"Bryan Singer,Patrick Stewart,Hugh Jackman,Ian ...",In a world where mutants (evolved super-powere...,"Faithful to the comics and filled with action,...",82,174,83,250000,MARVEL,4
4,5,Blade II,2002,"Action, Fantasy, Horror",117,R,6.7,203813,82350000,Guillermo del Toro,"Guillermo del Toro,Wesley Snipes,Kris Kristoff...",Blade forms an uneasy alliance with the vampir...,Though Blade II offers more of what worked in ...,57,150,68,250000,MARVEL,5

In [4]:
#checking data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      90 non-null     int64
 1   title           90 non-null     object
 2   year            90 non-null     int64
 3   genre           90 non-null     object
 4   runtime         90 non-null     int64
 5   mpa_rating      90 non-null     object
 6   imdb_rating     90 non-null     float64
 7   imdb_votes      90 non-null     int64
 8   imdb_gross      90 non-null     int64
 9   director        90 non-null     object
 10  stars           90 non-null     object
 11  description     90 non-null     object
 12  crit_consensus  90 non-null     object
 13  tomato_meter    90 non-null     int64
 14  tomato_review   90 non-null     int64
 15  tom_aud_score   90 non-null     int64
 16  tom_ratings     90 non-null     int64
 17  entity          90 non-null     object
 18  id              90 non-null     int64
dtypes: float64(1), int64(10), object(8)
memory usage: 13.5+ KB

In [5]:
#summary statistics
df.describe()

,Unnamed: 0,year,runtime,imdb_rating,imdb_votes,imdb_gross,tomato_meter,tomato_review,tom_aud_score,tom_ratings,id
count,90.000000,90.000000,90.000000,90.000000,9.000000e+01,9.000000e+01,90.000000,90.000000,90.000000,90.000000,90.000000
mean,45.500000,2006.377778,124.144444,6.552222,4.652830e+05,2.123682e+08,59.900000,266.966667,66.733333,150311.111111,45.500000
std,26.124701,14.335920,23.522192,1.271576,3.834906e+05,1.737576e+08,29.439731,144.250597,22.646179,98166.343799,26.124701
min,1.000000,1944.000000,58.000000,2.900000,8.440000e+02,0.000000e+00,0.000000,1.000000,15.000000,250.000000,1.000000
25%,23.250000,2003.250000,110.500000,5.700000,1.910570e+05,7.757250e+07,31.250000,156.250000,55.250000,50000.000000,23.250000
50%,45.500000,2011.000000,124.000000,6.900000,4.212640e+05,1.806150e+08,67.500000,277.500000,73.500000,100000.000000,45.500000
75%,67.750000,2016.000000,136.000000,7.400000,6.548668e+05,3.249725e+08,85.750000,377.250000,85.000000,250000.000000,67.750000
max,90.000000,2020.000000,244.000000,9.000000,2.369304e+06,8.583700e+08,96.000000,585.000000,95.000000,250000.000000,90.000000

In [6]:
#checking the number of unique values per column
df.nunique()

Unnamed: 0        90
title             89
year              35
genre             21
runtime           57
mpa_rating         5
imdb_rating       40
imdb_votes        90
imdb_gross        86
director          63
stars             90
description       90
crit_consensus    90
tomato_meter      51
tomato_review     86
tom_aud_score     52
tom_ratings        8
entity             2
id                90
dtype: int64

In [7]:
#checking to see how many zeros exist in the numerical columns
zero_counts = (df[['runtime', 'imdb_rating', 'imdb_votes', 'imdb_gross', 'tomato_meter', 'tom_aud_score']] ==0 ).sum()
print("Count zeros per coulmn:")
print(zero_counts)

Count zeros per coulmn:
runtime          0
imdb_rating      0
imdb_votes       0
imdb_gross       5
tomato_meter     2
tom_aud_score    0
dtype: int64

In [8]:
#inspecting the movies where imdb_gross is 0
print("Movies with 0 gross:")
display(df.loc[df['imdb_gross'] == 0, ['title', 'year', 'entity', 'imdb_gross']])

#inspecting the movies where tomato_meter is 0
print("\nMovies with 0 tomato_meter:")
display(df.loc[df['tomato_meter'] == 0, ['title', 'year', 'entity', 'tomato_meter']])

Movies with 0 gross:

                        title  year  entity  imdb_gross
0             Captain America  1944  MARVEL           0
56            The New Mutants  2020  MARVEL           0
57  Superman and the Mole-Men  1951      DC           0
58          Batman: The Movie  1966      DC           0
61                Swamp Thing  1982      DC           0

Movies with 0 tomato_meter:

                        title  year  entity  tomato_meter
0             Captain America  1944  MARVEL             0
57  Superman and the Mole-Men  1951      DC             0

In [9]:
#replace 0s with NaN for columns where 0 means missing values
cols_to_fix = ['imdb_gross', 'tomato_meter']
df[cols_to_fix] = df[cols_to_fix].replace(0, np.nan)

In [12]:
#check for duplicate rows
print(f"Number of duplicate rows: {df.duplicated().sum()}")

Number of duplicate rows: 0

In [14]:
#drop redunt coulmns if they exist
if 'Unnamed: 0' in df.columns:
    df = df.drop(columns=['Unnamed: 0'])

print(df.columns.tolist())

['title', 'year', 'genre', 'runtime', 'mpa_rating', 'imdb_rating', 'imdb_votes', 'imdb_gross', 'director', 'stars', 'description', 'crit_consensus', 'tomato_meter', 'tomato_review', 'tom_aud_score', 'tom_ratings', 'entity', 'id']

In [16]:
#saved cleaned up data to csv
df.to_csv('../data/processed/cleaned_marvel_dc_movies.csv', index=False)

print("Data wrangling complete! Cleaned dataset successfully saved.")

Data wrangling complete! Cleaned dataset successfully saved.

In [17]:
# Aggregate key metrics to compare Marvel vs. DC
summary_table = df.groupby('entity').agg(
    Total_Movies=('title', 'count'),
    Mean_IMDb_Rating=('imdb_rating', lambda x: round(x.mean(), 2)),
    Median_IMDb_Rating=('imdb_rating', 'median'),
    Mean_Tomatoes=('tomato_meter', lambda x: round(x.replace(0, float('nan')).mean(), 1)),
    Mean_Gross_Millions=('imdb_gross', lambda x: round(x.replace(0, float('nan')).mean() / 1e6, 2))
).reset_index()

# Display the final summary table
print("=== MARVEL VS. DC: FINAL COMPARISON SUMMARY ===")
display(summary_table)

=== MARVEL VS. DC: FINAL COMPARISON SUMMARY ===

,entity,Total_Movies,Mean_IMDb_Rating,Median_IMDb_Rating,Mean_Tomatoes,Mean_Gross_Millions
0,DC,33,6.13,6.1,54.1,176.97
1,MARVEL,57,6.79,7.0,65.4,250.98

In [18]:
#Even though Marvel has 24 more movies, Marvel has a significantly larger mean gross than DC films as well as a higher rating for both
# imdb and rotten tomatoes.